SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `tatry` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `tatry` ;

-- -----------------------------------------------------
-- Table `tatry`.`szczyt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tatry`.`szczyt` (
  `szczyt_id` INT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL,
  `wysokosc` INT NULL,
  PRIMARY KEY (`szczyt_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
